### ISSUE TITLE
How do you train new words ? 

### ISSUE THREAD

**Issue by zammitjames** [RomelioTavas/Speech-Recognition-ANN#1]
Hey! First off great speech recognition! i was curious how do you get it to learn new words please ? Thanks!

**Comment by bongtavas** [comment]
Hello. I've updated the README.md to contain steps on how to add new words. Enjoy =)

**Comment by zammitjames** [comment]
Thank you so much! I've been playing with it, it's really quite good! Well done and thank you for sharing this code :) Do you have any idea how I can make it continuous ? For example having the program continually listen without stopping or having to press anything and translating the text in real time ?

**Comment by bongtavas** [comment]
There are a lot of things to consider. First, how will you filter out noise when you're recording continuously? Second, how will you detect if there is a voice activity going on so you can capture it? You can look at topics like Voice Activity Detection (VAD) to get you started.

**Comment by zammitjames** [comment]
Thank you :)
